"""empty message

Revision ID: 371d493aec39
Revises: 6f7ba25472bd
Create Date: 2019-06-17 16:02:26.498795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371d493aec39'
down_revision = '6f7ba25472bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_pid_key', 'Show', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Show_pid_key', 'Show', ['pid'])
    # ### end Alembic commands ###
