"""empty message

Revision ID: 6f7ba25472bd
Revises: 
Create Date: 2019-06-17 15:51:30.874555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f7ba25472bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('pid')
    )
    op.create_table('LastUpdate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ShowMatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.Integer(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_id'),
    sa.UniqueConstraint('show_id')
    )
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.String(), nullable=True),
    sa.Column('show_title', sa.String(), nullable=True),
    sa.Column('show_season', sa.Integer(), nullable=True),
    sa.Column('show_episode', sa.Integer(), nullable=True),
    sa.Column('show_details', sa.String(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['Channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    op.drop_table('ShowMatch')
    op.drop_table('LastUpdate')
    op.drop_table('Channel')
    # ### end Alembic commands ###
