name: Unit Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install Pytest
        run: pip install pytest
          
      - name: Install Pytest Coverage
        run: pip install pytest-cov
        
      - name: Create a conftest (for pytest to be able to import modules)
        run: touch conftest.py
    
      - name: Run tests with pytest
        run: pytest --cov=.
      
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit Test
          github-token: ${{ secrets.GITHUB_TOKEN }}

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
